services:
  - type: web
    name: przeglad-awm-portal
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: AWM_API_KEY
        generateValue: true
      - key: AWM_DATA_DIR
        value: /var/data/awm_portal
    disk:
      name: awm-data
      mountPath: /var/data
      sizeGB: 1
